###░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░###
###░░░░░░░░░░█████╗░██████╗░██╗░░░██╗██████╗░████████╗██████╗░░█████╗░████████╗░░░░░░░░░###
###░░░░░░░░░██╔══██╗██╔══██╗╚██╗░██╔╝██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗╚══██╔══╝░░░░░░░░░###
###░░░░░░░░░██║░░╚═╝██████╔╝░╚████╔╝░██████╔╝░░░██║░░░██████╦╝██║░░██║░░░██║░░░░░░░░░░░░###
###░░░░░░░░░██║░░██╗██╔══██╗░░╚██╔╝░░██╔═══╝░░░░██║░░░██╔══██╗██║░░██║░░░██║░░░░░░░░░░░░###
###░░░░░░░░░╚█████╔╝██║░░██║░░░██║░░░██║░░░░░░░░██║░░░██████╦╝╚█████╔╝░░░██║░░░░░░░░░░░░###
###░░░░░░░░░░╚════╝░╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░░░░░░░╚═╝░░░╚═════╝░░╚════╝░░░░╚═╝░░░░░░░░░░░░###
###░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ V 1.50 BY REGIUSS ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░###

DEBUG: false
CheckUpdate: true
AutoUpdate: true

#Настройка антикапчи
Сaptcha:
  #Types:
  #1-anti-captcha (для использования загрузите chromedriver)
  #2-capmonster
  type: 2
  AntiCaptchaAPIKey: "key"
  CapmonsterAPIKey: "key"

WaxAccountLogin:
  try_count: 50 #Количество попыток входа
  wait_login_wax_account: 60 #Пауза после неудачной попытки входа (в секундах)
  wait_login_wax_account_5: 300 #Пауза после каждой 5-ой неудачной попытки входа (в секундах)

Signatures:
  try_count: 20 #Количество попыток получения сигнатур
  wait_on_error: 60 # Время в секундах для ожидания после ошибки

Resources:
  check: true #Проверять количество ресурсов перед началом майнинга
  wait: 300 #Пауза перед повторной проверкой ресурсов
  min: 600 #Минимальное количество ресурсов для начала майнинга

#Ожидание при ошибках (в секундах)
Errors:
  ResourcesWait: 120 #Нехватка ресурсов (CPU, NET, RAM)
  MineTooSoon: 120 #Mine to soon (офигенное описание да?)
  OtherError: 300 #Любая другая ошибка
